#logging:
#  level:
#    root: error
spring:
  redis:
    #host: 10.15.3.32
    host: 172.16.108.202
    port: 6379
    database: 1
    password:
    timeout: 5000ms
server:
  port: 8080
config:
  jwt:
    # 加密密钥
    secret: abcdefg1234567
    # token有效时长 (分钟)
    expire: 2
    # header 名称
    header: token